/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

 /*
 * The pluginManagement {} block may only appear in either the settings.gradle file, where it must be the first block in the file, or in an Initialization Script(init.gradle.kts, https://docs.gradle.org/current/userguide/init_scripts.html)
 * https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

rootProject.name = "sharingeconomy.pk.pricedispersion.datacollection.frontend"
rootProject.buildFileName = "build.gradle.kts"
include("app")
